name: Deploy to Vertex AI

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true


      - name: Build and push Docker image
        run: |
          # Build your Docker image
          docker build -t model-image .
          docker images
          docker tag model-image us-docker.pkg.dev/genuine-quasar-425514-f6/demo-project/model-img
          docker images
          docker push us-docker.pkg.dev/genuine-quasar-425514-f6/demo-project/model-img
          #ls
         # docker info | grep "Storage Driver"
